apiVersion: v1
kind: Service
metadata:
  name: okultakip-backend
  labels:
    app: okultakip
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: okultakip
    component: backend
